{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "JWT Pizza Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", endpoint=\"[DELETE] /\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", endpoint=\"[GET] /\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", endpoint=\"[PUT] /\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\", endpoint=\"[POST] /\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "sum by(source) (rate(requests_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "JWT Pizza Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_avg_milliseconds{source=\"jwt-pizza-service\", endpoint=\"[GET] /\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "latency_avg_milliseconds{source=\"jwt-pizza-service\", endpoint=\"[POST] /\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "latency_avg_milliseconds{source=\"jwt-pizza-service\", endpoint=\"[DELETE] /\"}",
     "legendFormat": "{{endpoint}}"
    },
    {
     "expr": "latency_avg_milliseconds{source=\"jwt-pizza-service\", endpoint=\"[PUT] /\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "JWT Pizza CPU and Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory Usage %"
    },
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU Usage %"
    }
   ]
  },
  {
   "title": "Revenue per minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_USD_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas sold and failed per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(pizza_successes_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Successes"
    },
    {
     "expr": "rate(pizza_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Pizza creation average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_latency_avg_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza creation"
    }
   ]
  },
  {
   "title": "Authentication counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "auth_attempts_success_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "auth_attempts_failure_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active users"
    }
   ]
  }
 ]
}